import type { Artwork, Collection } from "./types";

/**
 * SAMPLE CONTENT — placeholder paintings and text used while the site is
 * being built. This will be replaced by Melissa's real work once the
 * content dashboard (Sanity) is connected.
 */

const palettes = {
  sunset: ["#f6c177", "#e9a23b", "#c8553d", "#8f2d56", "#3d1e3f"],
  coast: ["#fbe3c8", "#f2a65a", "#2a9d8f", "#1f6f6b", "#264653"],
  garden: ["#fde2e4", "#f4978e", "#e56b6f", "#6a994e", "#386641"],
  citrus: ["#fff3b0", "#e9c46a", "#f4a261", "#e76f51", "#6b2d5c"],
  plum: ["#f3d9c9", "#d8a7b1", "#b56576", "#6b2d5c", "#355070"],
  meadow: ["#f1faee", "#e9d8a6", "#ee9b00", "#94d2bd", "#005f73"],
} as const;

export const sampleCollections: Collection[] = [
  {
    slug: "sun-drenched",
    title: "Sun-Drenched",
    summary: "Landscapes soaked in late-afternoon light.",
    description: [
      "Hillsides, coastlines and open fields painted in the warm hour before sunset.",
      "This series began with small plein-air studies and grew into larger studio paintings.",
    ],
    cover: "golden-hour-hills",
  },
  {
    slug: "garden-party",
    title: "Garden Party",
    summary: "Loose, joyful florals in full bloom.",
    description: [
      "Blooms from the garden, painted quickly and loosely to keep them fresh.",
    ],
    cover: "peonies-in-june",
  },
  {
    slug: "color-studies",
    title: "Color Studies",
    summary: "Abstract experiments in color and movement.",
    description: [
      "Paintings about color itself: how one warm hue changes next to another.",
    ],
    cover: "marigold-rhythm",
  },
  {
    slug: "big-and-bold",
    title: "Big & Bold",
    summary: "Large-scale statement pieces, up to 5 feet.",
    description: [
      "Large canvases made to anchor a room. Most of these are available by inquiry so shipping and installation can be arranged personally.",
    ],
    cover: "tidewater",
  },
];

export const sampleArtworks: Artwork[] = [
  {
    slug: "golden-hour-hills",
    title: "Golden Hour Hills",
    year: 2025,
    medium: "Acrylic on canvas",
    widthIn: 36,
    heightIn: 24,
    description: [
      "Rolling hills catching the last light of the day. Layers of marigold and rose were built up to glow through the shadows.",
    ],
    collections: ["sun-drenched"],
    featured: true,
    original: { status: "available", saleMode: "buy-now", price: 185000 },
    printsEnabled: true,
    placeholder: { seed: 11, palette: palettes.sunset, style: "landscape" },
  },
  {
    slug: "peonies-in-june",
    title: "Peonies in June",
    year: 2025,
    medium: "Oil on canvas",
    widthIn: 16,
    heightIn: 20,
    description: [
      "A bunch of peonies from the garden, painted in one sitting before they opened too far.",
    ],
    collections: ["garden-party"],
    featured: true,
    original: { status: "available", saleMode: "buy-now", price: 95000 },
    printsEnabled: true,
    placeholder: { seed: 23, palette: palettes.garden, style: "floral" },
  },
  {
    slug: "marigold-rhythm",
    title: "Marigold Rhythm",
    year: 2024,
    medium: "Acrylic and oil pastel on canvas",
    widthIn: 30,
    heightIn: 30,
    description: [
      "Loose, rhythmic marks in marigold, teal and plum. Painted to music, one layer per song.",
    ],
    collections: ["color-studies"],
    featured: true,
    original: { status: "sold", saleMode: "buy-now", price: 160000 },
    printsEnabled: true,
    placeholder: { seed: 37, palette: palettes.citrus, style: "abstract" },
  },
  {
    slug: "tidewater",
    title: "Tidewater",
    year: 2025,
    medium: "Acrylic on canvas",
    widthIn: 60,
    heightIn: 60,
    description: [
      "A five-foot square painting of the tide pulling out at dusk. Made to fill a wall.",
    ],
    collections: ["big-and-bold", "sun-drenched"],
    featured: true,
    original: { status: "available", saleMode: "inquire", price: 650000 },
    printsEnabled: true,
    placeholder: { seed: 41, palette: palettes.coast, style: "landscape" },
  },
  {
    slug: "citrus-grove",
    title: "Citrus Grove",
    year: 2024,
    medium: "Oil on panel",
    widthIn: 12,
    heightIn: 12,
    description: ["A small study of orange trees in the midday sun."],
    collections: ["sun-drenched"],
    original: { status: "available", saleMode: "buy-now", price: 42000 },
    printsEnabled: true,
    placeholder: { seed: 53, palette: palettes.citrus, style: "landscape" },
  },
  {
    slug: "plum-season",
    title: "Plum Season",
    year: 2024,
    medium: "Acrylic on canvas",
    widthIn: 24,
    heightIn: 30,
    description: [
      "Deep plum and dusty rose shapes pushing against each other.",
    ],
    collections: ["color-studies"],
    original: { status: "available", saleMode: "buy-now", price: 120000 },
    printsEnabled: true,
    placeholder: { seed: 67, palette: palettes.plum, style: "abstract" },
  },
  {
    slug: "wildflower-field",
    title: "Wildflower Field",
    year: 2023,
    medium: "Oil on canvas",
    widthIn: 40,
    heightIn: 30,
    description: ["A roadside field of wildflowers in early summer."],
    collections: ["garden-party", "sun-drenched"],
    original: { status: "sold", saleMode: "buy-now", price: 210000 },
    printsEnabled: true,
    placeholder: { seed: 71, palette: palettes.meadow, style: "floral" },
  },
  {
    slug: "coral-and-teal",
    title: "Coral & Teal",
    year: 2025,
    medium: "Acrylic on canvas",
    widthIn: 48,
    heightIn: 60,
    description: [
      "A large abstract built from sweeping coral strokes over a deep teal ground.",
    ],
    collections: ["big-and-bold", "color-studies"],
    original: { status: "available", saleMode: "inquire-private" },
    printsEnabled: true,
    placeholder: { seed: 83, palette: palettes.coast, style: "abstract" },
  },
  {
    slug: "ranunculus",
    title: "Ranunculus",
    year: 2025,
    medium: "Oil on canvas",
    widthIn: 12,
    heightIn: 16,
    description: ["Three ranunculus stems in a blue glass jar."],
    collections: ["garden-party"],
    original: { status: "available", saleMode: "buy-now", price: 55000 },
    printsEnabled: true,
    placeholder: { seed: 97, palette: palettes.garden, style: "floral" },
  },
  {
    slug: "desert-bloom",
    title: "Desert Bloom",
    year: 2023,
    medium: "Acrylic on canvas",
    widthIn: 20,
    heightIn: 20,
    description: ["A cactus flower opening against a hot pink sky."],
    collections: ["garden-party", "color-studies"],
    archived: true,
    original: { status: "not-for-sale", saleMode: "buy-now" },
    printsEnabled: true,
    placeholder: { seed: 101, palette: palettes.sunset, style: "floral" },
  },
  {
    slug: "harbor-morning",
    title: "Harbor Morning",
    year: 2024,
    medium: "Oil on canvas",
    widthIn: 30,
    heightIn: 20,
    description: ["Boats resting in the harbor as the fog lifts."],
    collections: ["sun-drenched"],
    original: { status: "sold", saleMode: "buy-now", price: 115000 },
    printsEnabled: false,
    placeholder: { seed: 113, palette: palettes.coast, style: "landscape" },
  },
  {
    slug: "sunburst",
    title: "Sunburst",
    year: 2025,
    medium: "Acrylic on canvas",
    widthIn: 48,
    heightIn: 48,
    description: [
      "A four-foot burst of yellow, orange and magenta. Pure energy.",
    ],
    collections: ["big-and-bold", "color-studies"],
    original: { status: "available", saleMode: "buy-now", price: 380000 },
    printsEnabled: true,
    placeholder: { seed: 127, palette: palettes.citrus, style: "abstract" },
  },
];
